const productos = [
  {
    marca: "Sony",
    tipo: "Consola",
    empresa: "Sony Interactive Entertainment",
    entidad: "PS5",
    genero: "Aventura",
    imagen:
      "https://estaticos.elcolombiano.com/binrepository/407x240/4c0/360d240/none/11101/DTLF/ps5-pro_46022536_20240910102823.jpg",
    precio: 2500,
    cantidad: 25,
    id: 1,
  },
  {
    marca: "Microsoft",
    tipo: "Consola",
    empresa: "Microsoft",
    entidad: "Xbox Series X",
    genero: "Acción",
    imagen:
      "https://tiendatecnologicadecolombia.com/wp-content/uploads/2021/05/xbox-series-x-2.jpg",
    precio: 1000,
    cantidad: 20,
    id: 2,
  },
  {
    marca: "Nintendo",
    tipo: "Consola",
    empresa: "Nintendo",
    entidad: "Switch",
    genero: "Plataformas",
    imagen:
      "https://http2.mlstatic.com/D_NQ_NP_803086-MLA47920649105_102021-O.webp",
    precio: 890,
    cantidad: 30,
    id: 3,
  },
  {
    marca: "Razer",
    tipo: "Controlador",
    empresa: "Razer Inc.",
    entidad: "Razer Wolverine",
    genero: "Competitivo",
    imagen:
      "https://www.pcdigital.com.mx/wp-content/uploads/2023/07/RZ20-04350100-R3U1.jpg",
    precio: 400,
    cantidad: 20,
    id: 4,
  },
  {
    marca: "Logitech",
    tipo: "Controlador",
    empresa: "Logitech",
    entidad: "Logitech G Pro",
    genero: "Competitivo",
    imagen:
      "https://tienda.dellthus.com/10063-large_default/camara-web-logitech-952-000091-hd-con-microfono-integrado.jpg",
    precio: 400,
    cantidad: 5,
    id: 5,
  },
  {
    marca: "Corsair",
    tipo: "Auriculares",
    empresa: "Corsair",
    entidad: "HS70",
    genero: "Audio",
    imagen:
      "https://imagedelivery.net/4fYuQyy-r8_rpBpcY7lH_A/falabellaCO/128256603_01/w=800,h=800,fit=pad",
    precio: 60,
    cantidad: 30,
    id: 6,
  },
  {
    marca: "HyperX",
    tipo: "Auriculares",
    empresa: "HyperX",
    entidad: "Cloud II",
    genero: "Audio",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROMZWLtFGFQB6VcjS5w6Rq4GmWlER_6JIVnA&s",
    precio: 70,
    cantidad: 22,
    id: 7,
  },
  {
    marca: "Sony",
    tipo: "Accesorio",
    empresa: "Sony",
    entidad: "PlayStation Camera",
    genero: "VR",
    imagen:
      "https://http2.mlstatic.com/D_NQ_NP_911545-CBT49418408050_032022-O.webp",
    precio: 250,
    cantidad: 50,
    id: 8,
  },
  {
    marca: "Oculus",
    tipo: "Consola",
    empresa: "Meta",
    entidad: "Oculus Quest 2",
    genero: "VR",
    imagen: "https://i.blogs.es/1745d9/oculus-rift-s-1/1366_2000.jpg",
    precio: 800,
    cantidad: 20,
    id: 9,
  },
  {
    marca: "Seagate",
    tipo: "Almacenamiento",
    empresa: "Seagate",
    entidad: "Game Drive",
    genero: "Accesorio",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjf9KBZBpF6QUXZ2LjY9o1fXMPIEBZijVxDw&s",
    precio: 300,
    cantidad: 10,
    id: 10,
  },
  {
    marca: "Turtle Beach",
    tipo: "Auriculares",
    empresa: "Turtle Beach",
    entidad: "Stealth 600",
    genero: "Audio",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD2zgQtOnsN1s-Emhy9ZP44jnn8OkdanRwrg&s",
    precio: 80,
    cantidad: 8,
    id: 11,
  },
  {
    marca: "Razer",
    tipo: "Teclado",
    empresa: "Razer Inc.",
    entidad: "BlackWidow",
    genero: "Competitivo",
    imagen:
      "https://http2.mlstatic.com/D_NQ_NP_708665-CBT53073625476_122022-O.webp",
    precio: 200,
    cantidad: 100,
    id: 12,
  },
  {
    marca: "Logitech",
    tipo: "Ratón",
    empresa: "Logitech",
    entidad: "G502 HERO",
    genero: "Competitivo",
    imagen:
      "https://www.pcware.com.co/wp-content/uploads/2020/12/Logitech-G502-HERO-25k.jpg",
    precio: 200,
    cantidad: 25,
    id: 13,
  },
  {
    marca: "ASUS",
    tipo: "Consola",
    empresa: "ASUS",
    entidad: "ROG Phone",
    genero: "Móvil",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGM0Nez3ecONda09Yj9SqmJLZAggxV3DR48Q&s",
    precio: 570,
    cantidad: 20,
    id: 14,
  },
  {
    marca: "Acer",
    tipo: "Monitor",
    empresa: "Acer",
    entidad: "Predator X27",
    genero: "Accesorio",
    imagen:
      "https://m.media-amazon.com/images/I/619-bQZm1uL._AC_UF894,1000_QL80_.jpg",
    precio: 700,
    cantidad: 10,
    id: 15,
  },
  {
    marca: "Dell",
    tipo: "Monitor",
    empresa: "Dell",
    entidad: "Alienware AW2521H",
    genero: "Accesorio",
    imagen:
      "https://http2.mlstatic.com/D_NQ_NP_600542-MLU78803995721_082024-O.webp",
    precio: 150,
    cantidad: 25,
    id: 16,
  },
  {
    marca: "Samsung",
    tipo: "Televisor",
    empresa: "Samsung",
    entidad: "QLED 4K",
    genero: "Accesorio",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHQ-up5jPmp0NTwuShzoQsYs1QHHcCGkBx6Q&s",
    precio: 400,
    cantidad: 30,
    id: 17,
  },
  {
    marca: "AMD",
    tipo: "GPU",
    empresa: "AMD",
    entidad: "Radeon RX 6800",
    genero: "Hardware",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZPC-KyI4OnoMiSgbR-MgGhQ7VJCswhfv3Xw&s",
    precio: 525,
    cantidad: 40,
    id: 18,
  },
  {
    marca: "NVIDIA",
    tipo: "GPU",
    empresa: "NVIDIA",
    entidad: "GeForce RTX 3080",
    genero: "Hardware",
    imagen:
      "https://altagamadigital.com/wp-content/uploads/2023/10/evga-geforce-rtx-3080-ftw316536521151-2.png.webp",
    precio: 510,
    cantidad: 208,
    id: 19,
  },
  {
    marca: "Alienware",
    tipo: "Laptop",
    empresa: "Dell",
    entidad: "Alienware m15",
    genero: "Hardware",
    imagen:
      "https://www.professionalwireless.com.co/wp-content/uploads/2023/07/INS0149583-R0020298-SA_3.png",
    precio: 320,
    cantidad: 300,
    id: 20,
  },
  {
    marca: "MSI",
    tipo: "Laptop",
    empresa: "MSI",
    entidad: "GS66 Stealth",
    genero: "Hardware",
    imagen:
      "https://storage-asset.msi.com/global/picture/image/feature/nb/GS66-76/images/GS66-D1.png",
    precio: 714,
    cantidad: 2,
    id: 21,
  },
  {
    marca: "Blue",
    tipo: "Micrófono",
    empresa: "Blue Microphones",
    entidad: "Yeti",
    genero: "Audio",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN-kFzCrmikR_4LPwlC-hsWSzGbsIsqdPMnQ&s",
    precio: 230,
    cantidad: 1000,
    id: 22,
  },
  {
    marca: "Elgato",
    tipo: "Capturadora",
    empresa: "Elgato",
    entidad: "HD60 S",
    genero: "Streaming",
    imagen:
      "https://http2.mlstatic.com/D_NQ_NP_680169-MCO50530600600_062022-O.webp",
    precio: 540,
    cantidad: 200,
    id: 23,
  },
  {
    marca: "Turtle Beach",
    tipo: "Auriculares",
    empresa: "Turtle Beach",
    entidad: "Recon 200",
    genero: "Competitivo",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPxEYQJscJKd4Ae8ckw2sqIXvtRgWcn_CgHA&s",
    precio: 100,
    cantidad: 70,
    id: 24,
  },
  {
    marca: "Valve",
    tipo: "Consola",
    empresa: "Valve",
    entidad: "Steam Deck",
    genero: "Portátil",
    imagen: "https://m.media-amazon.com/images/I/51TEmAZN6rL.jpg",
    precio: 90,
    cantidad: 70,
    id: 25,
  },
  {
    marca: "Bandai Namco",
    tipo: "Juego",
    empresa: "Bandai Namco Entertainment",
    entidad: "Tekken 7",
    genero: "Lucha",
    imagen:
      "https://image.api.playstation.com/cdn/UP0700/CUSA05972_00/4yfeeKKfJdD5WzDQsoiM3xrcqPlpDLm7.png",
    precio: 80,
    cantidad: 10,
    id: 26,
  },
  {
    marca: "Ubisoft",
    tipo: "Juego",
    empresa: "Ubisoft",
    entidad: "Assassin's Creed Valhalla",
    genero: "Aventura",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR72JdVqDDtvrxy9nx4vnfA5kuEdZCLynJXfg&s",
    precio: 50,
    cantidad: 25,
    id: 27,
  },
  {
    marca: "Activision",
    tipo: "Juego",
    empresa: "Activision",
    entidad: "Call of Duty: Warzone",
    genero: "Shooter",
    imagen:
      "https://image.api.playstation.com/vulcan/ap/rnd/202409/1019/ecea7baca0cf165c66506f34f88619c8d05b8bf3c3386c71.png?w=440",
    precio: 220,
    cantidad: 10,
    id: 28,
  },
  {
    marca: "Epic Games",
    tipo: "Juego",
    empresa: "Epic Games",
    entidad: "Fortnite",
    genero: "Battle Royale",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3-WWDfswBEQD7qgAvkE12vQiJjE2RVWPExQ&s",
    precio: 0,
    cantidad: 500,
    id: 29,
  },
  {
    marca: "Riot Games",
    tipo: "Juego",
    empresa: "Riot Games",
    entidad: "League of Legends",
    genero: "MOBA",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwFjfKGZLksg6DQ1L2qHfjnbz1qETbf5IT_w&s",
    precio: 30,
    cantidad: 30,
    id: 30,
  },
  {
    marca: "Nintendo",
    tipo: "Juego",
    empresa: "Nintendo",
    entidad: "The Legend of Zelda: Breath of the Wild",
    genero: "Aventura",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5O00EydKudnPPUPdZn-NFu7BWhtIU6LCnkQ&s",
    precio: 200,
    cantidad: 6,
    id: 31,
  },
  {
    marca: "Square Enix",
    tipo: "Juego",
    empresa: "Square Enix",
    entidad: "Final Fantasy VII Remake",
    genero: "RPG",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-S5ulbz5O-7hbrqMLCE5bSNUxiD3AdhvSBA&s",
    precio: 4,
    cantidad: 30,
    id: 32,
  },
  {
    marca: "FromSoftware",
    tipo: "Juego",
    empresa: "FromSoftware",
    entidad: "Dark Souls III",
    genero: "RPG",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCoF8yyQJpwgMVHJ-4Y8ioeKEof-8Q6xejuw&s",
    precio: 60,
    cantidad: 1,
    id: 33,
  },
  {
    marca: "Bungie",
    tipo: "Juego",
    empresa: "Bungie",
    entidad: "Destiny 2",
    genero: "Shooter",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwxanfeivYHzvx13u6Z3SXF2_MftnjSMKptA&s",
    precio: 70,
    cantidad: 5,
    id: 34,
  },
  {
    marca: "Blizzard",
    tipo: "Juego",
    empresa: "Blizzard Entertainment",
    entidad: "Overwatch",
    genero: "Shooter",
    imagen:
      "https://upload.wikimedia.org/wikipedia/en/thumb/5/51/Overwatch_cover_art.jpg/220px-Overwatch_cover_art.jpg",
    precio: 120,
    cantidad: 20,
    id: 35,
  },
  {
    marca: "Capcom",
    tipo: "Juego",
    empresa: "Capcom",
    entidad: "Monster Hunter: World",
    genero: "Aventura",
    imagen:
      "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/582010/capsule_616x353.jpg?t=1730268377",
    precio: 200,
    cantidad: 50,
    id: 36,
  },
  {
    marca: "CD Projekt",
    tipo: "Juego",
    empresa: "CD Projekt Red",
    entidad: "Cyberpunk 2077",
    genero: "RPG",
    imagen:
      "https://image.api.playstation.com/vulcan/ap/rnd/202311/2812/ae84720b553c4ce943e9c342621b60f198beda0dbf533e21.jpg",
    precio: 200,
    cantidad: 20,
    id: 37,
  },
  {
    marca: "Sega",
    tipo: "Juego",
    empresa: "Sega",
    entidad: "Sonic Mania",
    genero: "Plataformas",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZAsD8U0kyb_Ekz9z2tyCiBCkPbnuv1SqiSA&s",
    precio: 100,
    cantidad: 8,
    id: 38,
  },
  {
    marca: "EA",
    tipo: "Juego",
    empresa: "Electronic Arts",
    entidad: "FIFA 21",
    genero: "Deportes",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1R5MjwYyIRPnauPyMBKWQbv_ds4iO4FGxZA&s",
    precio: 70,
    cantidad: 10,
    id: 39,
  },
  {
    marca: "Rockstar",
    tipo: "Juego",
    empresa: "Rockstar Games",
    entidad: "GTA V",
    genero: "Acción",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpGCui9RLEUm5O9uHpynj7oYWD_9r_MPPgBQ&s",
    precio: 140,
    cantidad: 15,
    id: 40,
  },
  {
    marca: "Bethesda",
    tipo: "Juego",
    empresa: "Bethesda Softworks",
    entidad: "Skyrim",
    genero: "RPG",
    imagen:
      "https://image.api.playstation.com/vulcan/ap/rnd/202110/2019/aDSOgerXg4V6sf5A7VzHiTun.jpg",
    precio: 60,
    cantidad: 40,
    id: 41,
  },
  {
    marca: "Konami",
    tipo: "Juego",
    empresa: "Konami",
    entidad: "PES 2021",
    genero: "Deportes",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQET8UqvcHai9TUZR_3gyKKyxsi29J7CscTog&s",
    precio: 20,
    cantidad: 100,
    id: 42,
  },
  {
    marca: "Bandai Namco",
    tipo: "Juego",
    empresa: "Bandai Namco Entertainment",
    entidad: "Dragon Ball Z: Kakarot",
    genero: "RPG",
    imagen:
      "https://media.vandal.net/m/70008/dragon-ball-z-kakarot-20201311445449_1.jpg",
    precio: 116,
    cantidad: 82,
    id: 43,
  },
  {
    marca: "Naughty Dog",
    tipo: "Juego",
    empresa: "Naughty Dog",
    entidad: "The Last of Us Part II",
    genero: "Aventura",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5Q62BmsgpiOep6kHBq2sFYkp-SCH1bAykMg&s",
    precio: 100,
    cantidad: 80,
    id: 44,
  },
  {
    marca: "Insomniac Games",
    tipo: "Juego",
    empresa: "Sony Interactive Entertainment",
    entidad: "Spider-Man: Miles Morales",
    genero: "Acción",
    imagen:
      "https://imagedelivery.net/4fYuQyy-r8_rpBpcY7lH_A/falabellaCO/10002792_1/w=800,h=800,fit=pad",
    precio: 100,
    cantidad: 75,
    id: 45,
  },
];
